# ©AngelaMos | 2026
# compose.cpu.yml

name: angela

services:
  nginx:
    image: nginx:alpine
    ports:
      - "${PORT:-7200}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    expose:
      - "5173"
    environment:
      - VITE_API_URL=/api
    restart: unless-stopped

  backend:
    build: ./backend
    expose:
      - "8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - WHISPER_MODEL=${WHISPER_MODEL:-base.en}
      - WHISPER_DEVICE=cpu
      - WAKEWORD_MODELS_DIR=/app/models
    volumes:
      - ./backend/models:/app/models:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      ollama:
        condition: service_started
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    expose:
      - "11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=30m
      - OLLAMA_ORIGINS=*
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped

volumes:
  ollama_data:
